version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web_nw
      - nginx_nw
  nginx:
    container_name: nginx
    build:
      context: docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "800:80"
    networks:
      - nginx_nw

networks:
  web_nw:
    external: true
  nginx_nw:
    external: true