version: '3.8'

services:
  frontend:
    container_name: front
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:1337:1337"
    command: "npm run dev"
    restart: always

#  nginx:
#    container_name: nginx
#    build:
#      context: docker/nginx/
#      dockerfile: Dockerfile
#    ports:
#      - "800:80"
